package workflow

import (
	"strings"

	actionpins "github.com/github/gh-aw/pkg/actionpins"
	"github.com/github/gh-aw/pkg/logger"
)

var actionPinsLog = logger.New("workflow:action_pins")

// Type aliases — callers within pkg/workflow use these names directly.

// ActionYAMLInput is defined in pkg/actionpins; aliased here so all files in
// pkg/workflow (action_cache.go, safe_outputs_actions.go, …) can reference
// the type without an explicit import.
type ActionYAMLInput = actionpins.ActionYAMLInput

// ActionPin is the pinned GitHub Action type from pkg/actionpins.
type ActionPin = actionpins.ActionPin

// ActionPinsData is the embedded JSON structure from pkg/actionpins.
type ActionPinsData = actionpins.ActionPinsData

// ContainerPin is the pinned container image type from pkg/actionpins.
type ContainerPin = actionpins.ContainerPin

// SHAResolver is the interface for resolving a GitHub Action's commit SHA for a given version tag.
// It aliases actionpins.SHAResolver so pkg/workflow files can reference it without a separate import.
type SHAResolver = actionpins.SHAResolver

// --------------------------------------------------------------------------
// Package-private helpers used throughout pkg/workflow
// --------------------------------------------------------------------------

// formatActionReference formats an action reference with repo, SHA, and version.
func formatActionReference(repo, sha, version string) string {
	return actionpins.FormatPinnedActionReference(repo, sha, version)
}

// formatActionCacheKey generates a cache key for action resolution.
func formatActionCacheKey(repo, version string) string {
	return actionpins.FormatCacheKey(repo, version)
}

// extractActionRepo extracts the action repository from a uses string.
func extractActionRepo(uses string) string {
	return actionpins.ExtractRepo(uses)
}

// extractActionVersion extracts the version from a uses string.
func extractActionVersion(uses string) string {
	return actionpins.ExtractVersion(uses)
}

// ghesArtifactPin holds the version tag and commit SHA for a GHES-compatible artifact action pin.
type ghesArtifactPin struct {
	version string
	sha     string
}

// ghesArtifactCompatPins contains hardcoded GHES-compatible artifact action pins.
// These are the highest v3.x releases that avoid the @actions/artifact v2.0.0+
// GHES incompatibility (validated against GHES 3.19.1 per gh-aw#29551).
// Hardcoded because action_pins.json is auto-generated by `make recompile` and
// only tracks the latest versions — v3.x entries would be stripped.
var ghesArtifactCompatPins = map[string]ghesArtifactPin{
	"actions/upload-artifact":   {version: "v3.2.2", sha: "c6a366c94c3e0affe28c06c8df20a878f24da3cf"},
	"actions/download-artifact": {version: "v3.1.0", sha: "a9bc5e6ef2cb54c177f32aa5726adaa15e7e2d59"},
}

// getActionPin returns the pinned reference for the latest version of the repo
// using only the embedded pins (no WorkflowData required).
func getActionPin(repo string) string {
	pins := actionpins.GetActionPinsByRepo(repo)
	if len(pins) == 0 {
		actionPinsLog.Printf("No embedded pins found for repo: %s", repo)
		return ""
	}
	return actionpins.FormatPinnedActionReference(repo, pins[0].SHA, pins[0].Version)
}

// getActionPin returns the pinned reference for the given repo, using GHES-compatible
// v3.x pins for artifact actions when c.ghesArtifactCompat is true.
//
// This is the preferred call site for code running inside a Compiler method, since it
// automatically honours the per-compilation GHES compat flag without any global state.
func (c *Compiler) getActionPin(repo string) string {
	if c.ghesArtifactCompat {
		if pin, ok := ghesArtifactCompatPins[repo]; ok {
			actionPinsLog.Printf("GHES compat: using %s@%s instead of latest", repo, pin.version)
			return actionpins.FormatPinnedActionReference(repo, pin.sha, pin.version)
		}
	}
	return getActionPin(repo)
}

// getCachedActionPinFromResolver returns the pinned action reference for repo,
// preferring dynamic resolution via resolver over the embedded pins.
// For use within pkg/workflow when only a resolver is available (no WorkflowData).
func getCachedActionPinFromResolver(repo string, resolver SHAResolver) string {
	ctx := &actionpins.PinContext{}
	if resolver != nil {
		ctx.Resolver = resolver
	}
	return actionpins.ResolveLatestActionPin(repo, ctx)
}

// --------------------------------------------------------------------------
// Package-private API — delegates to pkg/actionpins with a PinContext from WorkflowData
// --------------------------------------------------------------------------

// getLatestActionPinByRepo returns the latest ActionPin for a given repository, if any.
func getLatestActionPinByRepo(repo string) (ActionPin, bool) {
	return actionpins.GetLatestActionPinByRepo(repo)
}

// getEmbeddedContainerPin returns the pinned container image for a given image reference.
func getEmbeddedContainerPin(image string) (actionpins.ContainerPin, bool) {
	return actionpins.GetContainerPin(image)
}

// lookupContainerPin returns the ContainerPin for the given image, checking cache first
// then falling back to embedded pins. Returns false if the image is not pinned.
func lookupContainerPin(image string, cache *ActionCache) (ContainerPin, bool) {
	if cache != nil {
		if pin, ok := cache.GetContainerPin(image); ok {
			return pin, true
		}
	}
	if pin, ok := getEmbeddedContainerPin(image); ok {
		return pin, true
	}
	return ContainerPin{}, false
}

// getActionPinWithData returns the pinned action reference for a given action@version,
// delegating to pkg/actionpins with a PinContext built from WorkflowData.
func getActionPinWithData(actionRepo, version string, data *WorkflowData) (string, error) {
	return actionpins.ResolveActionPin(actionRepo, version, data.PinContext())
}

// getCachedActionPin returns the pinned action reference for a given repository,
// preferring the dynamic resolver from WorkflowData over the embedded pins.
func getCachedActionPin(repo string, data *WorkflowData) string {
	return actionpins.ResolveLatestActionPin(repo, data.PinContext())
}

// --------------------------------------------------------------------------
// Step-level helpers that depend on WorkflowStep (stay in pkg/workflow)
// --------------------------------------------------------------------------

// applyActionPinToTypedStep applies SHA pinning to a WorkflowStep if it uses an action.
// Returns a modified copy of the step with pinned references.
// If the step doesn't use an action or the action is not pinned, returns the original step.
func applyActionPinToTypedStep(step *WorkflowStep, data *WorkflowData) *WorkflowStep {
	if step == nil || !step.IsUsesStep() {
		return step
	}

	actionRepo := extractActionRepo(step.Uses)
	if actionRepo == "" {
		return step
	}

	version := extractActionVersion(step.Uses)
	if version == "" {
		return step
	}

	// Strip the comment suffix before checking if it's already a SHA.
	// Uses strings like "repo@sha # version" are treated as already-pinned.
	rawVersion, _, _ := strings.Cut(version, " ")

	pinnedRef, err := getActionPinWithData(actionRepo, rawVersion, data)
	if err != nil || pinnedRef == "" {
		actionPinsLog.Printf("Skipping pin for %s@%s: no pin available", actionRepo, rawVersion)
		return step
	}

	actionPinsLog.Printf("Pinned action: %s@%s -> %s", actionRepo, rawVersion, pinnedRef)
	result := step.Clone()
	result.Uses = pinnedRef
	return result
}

// applyActionPinsToTypedSteps applies SHA pinning to a slice of typed WorkflowStep pointers.
// Returns a new slice with pinned references.
func applyActionPinsToTypedSteps(steps []*WorkflowStep, data *WorkflowData) []*WorkflowStep {
	if steps == nil {
		return nil
	}

	result := make([]*WorkflowStep, 0, len(steps))
	for _, step := range steps {
		if step == nil {
			result = append(result, nil)
			continue
		}
		result = append(result, applyActionPinToTypedStep(step, data))
	}
	return result
}
